# Build settings
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

name:               "Front Fest"

author:
  name:             Front Fest
  twitter:          frontfest
  github:           frontfest
  email:            frontfest@gmail.com

# Google-analytics
google-analytics:
  id:               "UA-86817262-2"

# URL
#url:                "https://AWEEKJ.github.io" # the base hostname & protocol for your site
#url:                "http://localhost:4000" # use this url when develop
#baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/Madrid
permalink:          /blog/:year/:month/:day/:title
# Pagination
paginate:           5
paginate_path:      /blog/page/:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
